Traceback (most recent call last):
  File "/home/danbot/Documents/code/data_analysis/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/danbot/Documents/code/data_analysis/lib/python3.10/site-packages/nbclient/client.py", line 1263, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/danbot/Documents/code/data_analysis/lib/python3.10/site-packages/nbclient/util.py", line 85, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/danbot/Documents/code/data_analysis/lib/python3.10/site-packages/nbclient/util.py", line 60, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/danbot/Documents/code/data_analysis/lib/python3.10/site-packages/nbclient/client.py", line 701, in async_execute
    await self.async_execute_cell(
  File "/home/danbot/Documents/code/data_analysis/lib/python3.10/site-packages/nbclient/client.py", line 1019, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/danbot/Documents/code/data_analysis/lib/python3.10/site-packages/nbclient/client.py", line 913, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
all_test_results = predict_entropy_from_attributes(df, holdout_pct)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn [9], line 1[0m
[0;32m----> 1[0m all_test_results [38;5;241m=[39m [43mpredict_entropy_from_attributes[49m[43m([49m[43mdf[49m[43m,[49m[43m [49m[43mholdout_pct[49m[43m)[49m

Cell [0;32mIn [8], line 18[0m, in [0;36mpredict_entropy_from_attributes[0;34m(df, holdout_pct)[0m
[1;32m     15[0m input_attributes [38;5;241m+[39m[38;5;241m=[39m attribute_set
[1;32m     16[0m input_data [38;5;241m=[39m df[input_attributes [38;5;241m+[39m [target_column]][38;5;241m.[39mcopy()
[0;32m---> 18[0m trial_df, test_df [38;5;241m=[39m [43mrun_trials[49m[43m([49m[43mbitrate[49m[43m,[49m[43m [49m[43mset_name[49m[43m,[49m[43m [49m[43minput_attributes[49m[43m,[49m[43m [49m[43mtarget_column[49m[43m,[49m[43m [49m[43minput_data[49m[43m,[49m[43m [49m[43mtrain_indices[49m[43m,[49m[43m [49m[43mtest_indices[49m[43m,[49m[43m [49m[43mn_optimization_rounds[49m[43m,[49m[43m [49m[43mnfolds[49m[43m,[49m[43m [49m[43mn_boost_rounds[49m[43m)[49m
[1;32m     20[0m test_rmse [38;5;241m=[39m root_mean_squared_error(test_df[[38;5;124m'[39m[38;5;124mactual[39m[38;5;124m'[39m], test_df[[38;5;124m'[39m[38;5;124mpredicted[39m[38;5;124m'[39m])
[1;32m     21[0m test_mae [38;5;241m=[39m mean_absolute_error(test_df[[38;5;124m'[39m[38;5;124mactual[39m[38;5;124m'[39m], test_df[[38;5;124m'[39m[38;5;124mpredicted[39m[38;5;124m'[39m])

Cell [0;32mIn [6], line 54[0m, in [0;36mrun_trials[0;34m(bitrate, set_name, features, target, input_data, train_indices, test_indices, n_optimization_rounds, nfolds, num_boost_rounds)[0m
[1;32m     52[0m [38;5;66;03m# print(lr, best_rmse_round, best_mae_round)[39;00m
[1;32m     53[0m [38;5;28mprint[39m(model_results)
[0;32m---> 54[0m [38;5;28mprint[39m([43masdf[49m)
[1;32m     56[0m results_dict [38;5;241m=[39m {
[1;32m     57[0m     [38;5;124m'[39m[38;5;124mbest_rmse_round[39m[38;5;124m'[39m: best_rmse_round,
[1;32m     58[0m     [38;5;124m'[39m[38;5;124mbest_mae_round[39m[38;5;124m'[39m: best_mae_round,
[0;32m   (...)[0m
[1;32m     64[0m     [38;5;124m'[39m[38;5;124mmin_train_rmse[39m[38;5;124m'[39m: model_results[38;5;241m.[39mloc[best_rmse_round, [38;5;124m'[39m[38;5;124mtrain-rmse-mean[39m[38;5;124m'[39m],
[1;32m     65[0m }
[1;32m     66[0m results_cols [38;5;241m=[39m [38;5;28mlist[39m(results_dict[38;5;241m.[39mkeys())

[0;31mNameError[0m: name 'asdf' is not defined
NameError: name 'asdf' is not defined

